### ISSUE TITLE
eth_newFilter returns filter id in 'UNFORMATTED DATA' format

### ISSUE THREAD

**Issue by kagel** [kagel/test#1]

**Comment by test-2016-07-06** [comment]
Current balance: 0.0000 ETH
![QR Code](http://commiteth.com/qr/kagel/test/bounty/1/b576dc95fbce8d45f9e70b6986fbc3555a268401640186ddf540762c3ad2240b/qr.png)
[http://commiteth.com](http://commiteth.com)

**Comment by test-2016-07-06** [comment]
Current balance: 669 ETH
![QR Code](http://localhost:3000/qr/kagel/test/bounty/1/b576dc95fbce8d45f9e70b6986fbc3555a268401640186ddf540762c3ad2240b/qr.png)
[http://localhost:3000](http://localhost:3000)

**Comment by test-2016-07-06** [comment]
Current balance: 0.00000000 ETH
![QR Code](http://commiteth.com/qr/kagel/test/bounty/1/b576dc95fbce8d45f9e70b6986fbc3555a268401640186ddf540762c3ad2240b/qr.png)
[http://commiteth.com](http://commiteth.com)
